// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/2fa/verify" | "/about" | "/academy" | "/academy/[slug]" | "/account" | "/account/security" | "/admin" | "/admin/academies" | "/admin/academies/[slug]/edit" | "/admin/academies/new" | "/admin/analytics" | "/admin/builder" | "/admin/certificates" | "/admin/courses" | "/admin/courses/[slug]/edit" | "/admin/courses/new" | "/admin/settings" | "/admin/staff" | "/admin/staff/roles" | "/admin/theme" | "/admin/users" | "/callback" | "/cart" | "/checkout" | "/checkout/success" | "/courses" | "/courses/[slug]" | "/courses/[slug]/lessons/[lessonSlug]" | "/edu-purchases" | "/events" | "/events/[slug]" | "/feed" | "/forgot-password" | "/groups" | "/login" | "/messages" | "/notifications" | "/offline" | "/privacy" | "/products" | "/products/[slug]" | "/profile/[userId]" | "/refunds" | "/register" | "/repair" | "/resend-verification" | "/reset-password" | "/search" | "/settings" | "/settings/account" | "/settings/account/danger" | "/settings/account/security" | "/settings/billing" | "/settings/connected-accounts" | "/settings/preferences/appearance" | "/settings/preferences/notifications" | "/settings/preferences/privacy" | "/settings/profile" | "/sponsors" | "/terms" | "/titan-tv" | "/u/[username]" | "/verify" | "/verify-email" | "/verify-email-change" | "/verify/[number]"
type AppRouteHandlerRoutes = "/api/proxy/[...path]" | "/api/proxy/tenants/[slug]"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/admin" | "/groups" | "/settings" | "/sponsors" | "/titan-tv"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/2fa/verify": {}
  "/about": {}
  "/academy": {}
  "/academy/[slug]": { "slug": string; }
  "/account": {}
  "/account/security": {}
  "/admin": {}
  "/admin/academies": {}
  "/admin/academies/[slug]/edit": { "slug": string; }
  "/admin/academies/new": {}
  "/admin/analytics": {}
  "/admin/builder": {}
  "/admin/certificates": {}
  "/admin/courses": {}
  "/admin/courses/[slug]/edit": { "slug": string; }
  "/admin/courses/new": {}
  "/admin/settings": {}
  "/admin/staff": {}
  "/admin/staff/roles": {}
  "/admin/theme": {}
  "/admin/users": {}
  "/api/proxy/[...path]": { "path": string[]; }
  "/api/proxy/tenants/[slug]": { "slug": string; }
  "/callback": {}
  "/cart": {}
  "/checkout": {}
  "/checkout/success": {}
  "/courses": {}
  "/courses/[slug]": { "slug": string; }
  "/courses/[slug]/lessons/[lessonSlug]": { "slug": string; "lessonSlug": string; }
  "/edu-purchases": {}
  "/events": {}
  "/events/[slug]": { "slug": string; }
  "/feed": {}
  "/forgot-password": {}
  "/groups": {}
  "/login": {}
  "/messages": {}
  "/notifications": {}
  "/offline": {}
  "/privacy": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/profile/[userId]": { "userId": string; }
  "/refunds": {}
  "/register": {}
  "/repair": {}
  "/resend-verification": {}
  "/reset-password": {}
  "/search": {}
  "/settings": {}
  "/settings/account": {}
  "/settings/account/danger": {}
  "/settings/account/security": {}
  "/settings/billing": {}
  "/settings/connected-accounts": {}
  "/settings/preferences/appearance": {}
  "/settings/preferences/notifications": {}
  "/settings/preferences/privacy": {}
  "/settings/profile": {}
  "/sponsors": {}
  "/terms": {}
  "/titan-tv": {}
  "/u/[username]": { "username": string; }
  "/verify": {}
  "/verify-email": {}
  "/verify-email-change": {}
  "/verify/[number]": { "number": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/admin": never
  "/groups": never
  "/settings": never
  "/sponsors": never
  "/titan-tv": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
