// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(admin)/admin/academies/[slug]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/academies/[slug]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/academies/[slug]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/academies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/academies/new">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/academies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/academies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/academies">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/academies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/builder">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/certificates">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/courses/[slug]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses/[slug]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/courses/[slug]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/courses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses/new">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/courses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/staff/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff/roles">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/staff/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/theme">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/2fa/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/2fa/verify">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/2fa/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/callback">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/resend-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resend-verification">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/resend-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/verify-email-change/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email-change">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/verify-email-change/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/account/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/security">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/account/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/courses/[slug]/lessons/[lessonSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[slug]/lessons/[lessonSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/courses/[slug]/lessons/[lessonSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/courses/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/courses/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/account/danger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account/danger">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/account/danger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/account/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/account/security">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/account/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/connected-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/connected-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/connected-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/preferences/appearance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/preferences/appearance">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/preferences/appearance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/preferences/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/preferences/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/preferences/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/preferences/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/preferences/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/preferences/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(social)/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feed">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(social)/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(social)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(social)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(social)/profile/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[userId]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(social)/profile/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(social)/repair/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repair">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(social)/repair/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/checkout/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout/success">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/checkout/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/academy/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/academy/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/edu-purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edu-purchases">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/edu-purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/groups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/groups">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/groups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/sponsors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sponsors">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/sponsors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/titan-tv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/titan-tv">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/titan-tv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/verify/[number]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify/[number]">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/verify/[number]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/proxy/tenants/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/tenants/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/proxy/tenants/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(academy)/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(academy)/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(social)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(social)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/(store)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/(store)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/groups/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/groups">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/groups/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/sponsors/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sponsors">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/sponsors/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(main)/titan-tv/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/titan-tv">> = Specific
  const handler = {} as typeof import("../../src/app/(main)/titan-tv/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
