import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import * as schema from '../schema';

export async function seedStudyGroups(
  db: PostgresJsDatabase<typeof schema>,
  hostId: string,
) {
  const now = new Date();

  await db.insert(schema.studyGroups).values([
    {
      hostId,
      name: 'Bay Area CNC Meetup',
      description: 'Regular meetup for CNC enthusiasts in the San Francisco Bay Area. All skill levels welcome.',
      academy: 'cnc',
      city: 'San Francisco',
      state: 'CA',
      lat: 37.7749,
      lng: -122.4194,
      meetingSchedule: 'First Saturday of each month',
      maxMembers: 30,
      memberCount: 18,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
    {
      hostId,
      name: 'Aerospace Machinists of Seattle',
      description: 'A group for aerospace machinists and engineers to share knowledge and network.',
      academy: 'aerospace',
      city: 'Seattle',
      state: 'WA',
      lat: 47.6062,
      lng: -122.3321,
      meetingSchedule: 'Every other Wednesday',
      maxMembers: 25,
      memberCount: 22,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
    {
      hostId,
      name: 'SoCal Grinding Guild',
      description: 'Specialized group focused on precision grinding techniques and tooling.',
      academy: 'grinding',
      city: 'Los Angeles',
      state: 'CA',
      lat: 34.0522,
      lng: -118.2437,
      meetingSchedule: 'Third Thursday monthly',
      maxMembers: 20,
      memberCount: 14,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
    {
      hostId,
      name: 'Swiss Precision Network',
      description: 'Network of Swiss-type machining professionals sharing best practices.',
      academy: 'swiss',
      city: 'Providence',
      state: 'RI',
      lat: 41.8240,
      lng: -71.4128,
      meetingSchedule: 'Bi-weekly on Fridays',
      maxMembers: 20,
      memberCount: 11,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
    {
      hostId,
      name: 'Texas CNC Collective',
      description: 'A growing community of CNC machinists across the Dallas-Fort Worth metroplex.',
      academy: 'cnc',
      city: 'Dallas',
      state: 'TX',
      lat: 32.7767,
      lng: -96.7970,
      meetingSchedule: 'Second Tuesday of each month',
      maxMembers: 35,
      memberCount: 27,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
    {
      hostId,
      name: 'Midwest Manufacturing Hub',
      description: 'Connect with manufacturers and machinists across the greater Chicago area.',
      academy: 'cnc',
      city: 'Chicago',
      state: 'IL',
      lat: 41.8781,
      lng: -87.6298,
      meetingSchedule: 'Weekly on Saturdays',
      maxMembers: 40,
      memberCount: 33,
      coverUrl: null,
      isActive: true,
      createdAt: now,
    },
  ]);

  console.log('Seeded study groups');
}
