import { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import * as schema from '../schema';

export async function seedEvents(db: PostgresJsDatabase<typeof schema>, tenantId: string) {
  await db.insert(schema.events).values([
    {
      tenantId, slug: 'cnc-workshop-2026',
      title: 'TITANS CNC Workshop 2026',
      description: 'Three-day hands-on CNC machining workshop covering setup, programming, and advanced techniques.',
      eventType: 'workshop',
      location: { venue: 'Austin Convention Center', address: '500 E Cesar Chavez St', city: 'Austin', state: 'TX', lat: 30.2634, lng: -97.7406 },
      startDate: new Date('2026-06-15T09:00:00Z'), endDate: new Date('2026-06-17T17:00:00Z'),
      maxAttendees: 200, isPublished: true,
    },
    {
      tenantId, slug: 'aerospace-symposium-2026',
      title: 'Aerospace Machining Symposium',
      description: 'Industry leaders share best practices for AS9100-compliant aerospace machining.',
      eventType: 'conference',
      location: { venue: 'Washington State Convention Center', address: '705 Pike St', city: 'Seattle', state: 'WA', lat: 47.6116, lng: -122.3327 },
      startDate: new Date('2026-08-10T09:00:00Z'), endDate: new Date('2026-08-11T17:00:00Z'),
      maxAttendees: 150, isPublished: true,
    },
    {
      tenantId, slug: 'swiss-masterclass-2026',
      title: 'Swiss Machining Masterclass',
      description: 'Intensive five-day course on Swiss-type lathe programming, tooling, and setup.',
      eventType: 'course',
      location: { venue: 'Providence Marriott', address: '1 Orms St', city: 'Providence', state: 'RI', lat: 41.8240, lng: -71.4128 },
      startDate: new Date('2026-09-21T09:00:00Z'), endDate: new Date('2026-09-25T17:00:00Z'),
      maxAttendees: 30, isPublished: true,
    },
    {
      tenantId, slug: 'west-coast-meetup-2026',
      title: 'Community Meetup: West Coast',
      description: 'One-day networking event for CNC professionals and hobbyists.',
      eventType: 'meetup',
      location: { venue: 'Los Angeles Convention Center', address: '1201 S Figueroa St', city: 'Los Angeles', state: 'CA', lat: 34.0400, lng: -118.2700 },
      startDate: new Date('2026-10-12T10:00:00Z'), endDate: new Date('2026-10-12T18:00:00Z'),
      maxAttendees: 100, isPublished: true,
    },
    {
      tenantId, slug: 'manufacturing-summit-2026',
      title: 'Year-End Manufacturing Summit',
      description: 'Annual summit reviewing industry trends, new technologies, and community achievements.',
      eventType: 'conference',
      location: { venue: 'McCormick Place', address: '2301 S King Dr', city: 'Chicago', state: 'IL', lat: 41.8526, lng: -87.6160 },
      startDate: new Date('2026-12-03T09:00:00Z'), endDate: new Date('2026-12-04T17:00:00Z'),
      maxAttendees: 300, isPublished: true,
    },
    {
      tenantId, slug: 'cnc-robotics-expo-2026',
      title: 'CNC & Robotics Expo',
      description: 'Explore the latest in CNC automation, robotic cells, and Industry 4.0 integration.',
      eventType: 'conference',
      location: { venue: 'Cobo Center', address: '1 Washington Blvd', city: 'Detroit', state: 'MI', lat: 42.3269, lng: -83.0487 },
      startDate: new Date('2026-07-20T09:00:00Z'), endDate: new Date('2026-07-22T17:00:00Z'),
      maxAttendees: 500, isPublished: true,
    },
    {
      tenantId, slug: 'milling-masterclass-dallas',
      title: 'Milling Masterclass: Dallas',
      description: 'Two-day intensive on advanced milling techniques, toolpath optimization, and surface finish.',
      eventType: 'course',
      location: { venue: 'Hilton Anatole', address: '2201 N Stemmons Fwy', city: 'Dallas', state: 'TX', lat: 32.7942, lng: -96.8156 },
      startDate: new Date('2026-11-08T09:00:00Z'), endDate: new Date('2026-11-09T17:00:00Z'),
      maxAttendees: 40, isPublished: true,
    },
    {
      tenantId, slug: 'online-speeds-feeds-webinar',
      title: 'Webinar: Feeds & Speeds Decoded',
      description: 'Free online webinar covering the fundamentals of speeds and feeds for CNC machining.',
      eventType: 'webinar',
      isVirtual: true,
      location: { venue: 'Online', city: 'Virtual', state: 'Online' },
      startDate: new Date('2026-05-15T18:00:00Z'), endDate: new Date('2026-05-15T19:30:00Z'),
      maxAttendees: 1000, isPublished: true,
    },
    {
      tenantId, slug: 'precision-grinding-workshop',
      title: 'Precision Grinding Workshop',
      description: 'Hands-on workshop covering surface, cylindrical, and centerless grinding techniques.',
      eventType: 'workshop',
      location: { venue: 'Technical College of Milwaukee', address: '815 W Villard Ave', city: 'Milwaukee', state: 'WI', lat: 43.1136, lng: -87.9143 },
      startDate: new Date('2026-08-05T08:00:00Z'), endDate: new Date('2026-08-06T16:00:00Z'),
      maxAttendees: 25, isPublished: true,
    },
    {
      tenantId, slug: 'toolmaking-bootcamp',
      title: 'Toolmaking Bootcamp',
      description: 'Intensive 3-day bootcamp on die making, jig design, and precision fixture construction.',
      eventType: 'course',
      location: { venue: 'Purdue University', address: '475 Stadium Mall Dr', city: 'West Lafayette', state: 'IN', lat: 40.4237, lng: -86.9212 },
      startDate: new Date('2026-09-14T09:00:00Z'), endDate: new Date('2026-09-16T17:00:00Z'),
      maxAttendees: 35, isPublished: true,
    },
    {
      tenantId, slug: 'additive-vs-subtractive',
      title: 'Additive vs Subtractive: The Debate',
      description: 'Panel discussion comparing 3D printing and CNC machining for production applications.',
      eventType: 'webinar',
      isVirtual: true,
      location: { venue: 'Online', city: 'Virtual', state: 'Online' },
      startDate: new Date('2026-06-28T17:00:00Z'), endDate: new Date('2026-06-28T18:30:00Z'),
      maxAttendees: 500, isPublished: true,
    },
    {
      tenantId, slug: 'houston-machinist-meetup',
      title: 'Houston Machinist Meetup',
      description: 'Monthly meetup for machinists in the Houston area. Shop tour included.',
      eventType: 'meetup',
      location: { venue: 'Houston MakerSpace', address: '1305 E 11th St', city: 'Houston', state: 'TX', lat: 29.7604, lng: -95.3698 },
      startDate: new Date('2026-05-22T18:30:00Z'), endDate: new Date('2026-05-22T21:00:00Z'),
      maxAttendees: 50, isPublished: true,
    },
    {
      tenantId, slug: 'cnc-tournament-2026',
      title: 'TITANS CNC Tournament',
      description: 'Live machining competition — fastest part with best surface finish wins.',
      eventType: 'competition',
      location: { venue: 'IMTS Pavilion', address: '2301 S Lake Shore Dr', city: 'Chicago', state: 'IL', lat: 41.8569, lng: -87.6099 },
      startDate: new Date('2026-10-20T09:00:00Z'), endDate: new Date('2026-10-21T17:00:00Z'),
      maxAttendees: 100, isPublished: true,
    },
  ]);
  console.log('Seeded 13 events');
}
